-- Traffic Accidents Cache Table
CREATE TABLE IF NOT EXISTS traffic_accidents_cache (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    lane_yn1 CHAR(1) COMMENT '1차로 여부',
    lane_yn2 CHAR(1) COMMENT '2차로 여부',
    lane_yn3 CHAR(1) COMMENT '3차로 여부',
    lane_yn4 CHAR(1) COMMENT '4차로 여부',
    lane_yn5 CHAR(1) COMMENT '5차로 여부',
    lane_yn6 CHAR(1) COMMENT '6차로 여부',
    late_length VARCHAR(50) COMMENT '지체길이',
    acc_hour VARCHAR(10) NOT NULL COMMENT '사고시간',
    acc_date VARCHAR(20) NOT NULL COMMENT '사고날짜',
    acc_type_code VARCHAR(10) COMMENT '사고유형코드',
    acc_type VARCHAR(50) COMMENT '사고유형',
    start_end_type_code VARCHAR(50) COMMENT '시종점유형코드',
    sms_text TEXT NOT NULL COMMENT 'SMS문자내용',
    acc_process_code VARCHAR(10) COMMENT '사고처리코드',
    acc_point_nm VARCHAR(100) COMMENT '사고지점명',
    nosun_nm VARCHAR(20) COMMENT '노선명',
    road_nm VARCHAR(50) COMMENT '도로명',
    acc_process_nm VARCHAR(20) COMMENT '사고처리명',
    latitude DECIMAL(10, 6) COMMENT '위도',
    altitude DECIMAL(10, 6) COMMENT '경도',
    series_nm INT COMMENT '순번',
    shldr_road_yn CHAR(1) COMMENT '갓길도로여부',
    collected_at TIMESTAMP NULL COMMENT '수집일시',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UNIQUE KEY uk_accident (acc_date, acc_hour, nosun_nm, road_nm, sms_text(255)),
    INDEX idx_date_time (acc_date, acc_hour),
    INDEX idx_collected_at (collected_at),
    INDEX idx_road (road_nm),
    INDEX idx_acc_type (acc_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='고속도로 실시간 교통사고 정보 캐시';

-- Tollgate Traffic Cache Table
CREATE TABLE IF NOT EXISTS tollgate_traffic_cache (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ex_div_code VARCHAR(10),
    ex_div_name VARCHAR(50),
    unit_code VARCHAR(10),
    unit_name VARCHAR(100),
    inout_type VARCHAR(10),
    inout_name VARCHAR(20),
    tm_type VARCHAR(10),
    tm_name VARCHAR(20),
    tcs_type VARCHAR(10),
    tcs_name VARCHAR(20),
    car_type VARCHAR(10),
    traffic_amount VARCHAR(20),
    sum_date VARCHAR(8),
    sum_tm VARCHAR(4),
    collected_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_tollgate (unit_code, sum_date, sum_tm, car_type, inout_type, tcs_type),
    INDEX idx_collected_at (collected_at),
    INDEX idx_unit_code (unit_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Road Traffic Status Cache Table
CREATE TABLE IF NOT EXISTS road_traffic_status_cache (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    route_no VARCHAR(10),
    route_name VARCHAR(100),
    conzone_id VARCHAR(20),
    conzone_name VARCHAR(100),
    vds_id VARCHAR(20),
    updown_type_code VARCHAR(10),
    traffic_amount VARCHAR(20),
    speed VARCHAR(10),
    share_ratio VARCHAR(10),
    time_avg VARCHAR(10),
    grade VARCHAR(10),
    std_date VARCHAR(8),
    std_hour VARCHAR(4),
    collected_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_road_status (vds_id, std_date, std_hour),
    INDEX idx_collected_at (collected_at),
    INDEX idx_route_no (route_no),
    INDEX idx_std_date_hour (std_date, std_hour)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
